image: archlinux:base-devel

stages:
    - check

shellcheck:
    stage: check
    before_script:
        - pacman -Sy
        - pacman --noconfirm -Sw glibc
        - pacman --noconfirm -S shellcheck
    script:
        - ./test/shellcheck-run.sh
