image: archlinux:base-devel

stages:
    - analysis

shellcheck:
    stage: analysis
    before_script:
        - pacman -Sy
        - pacman --noconfirm --quiet -S shellcheck
    script:
        - ./test/shellcheck-run.sh
